cache_dir: "../tensorleap/data/glue_sst/"

train_size: 50
val_size: 10
test_size: 5

ul_size: 5

max_length: 512

labels:
  - "Positive"
  - "Negative"
  - "Neutral"


"Negative": 0
"Positive": 1,
"Neutral": -1,


special_token_id: -100
CLS_ID: 101
SEP_ID: 102
